version: '3.3'

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql

  php-fpm:
      build: .
      depends_on:
          - mysql
      volumes:
          - ../:/var/www/:cached
      command: bin/console server:run 0.0.0.0:80
      ports:
          - 8000:80
volumes:
  db_data: {}
